name: "HomeDoudou"
description: "Addon pour connecter Arduino à Home Assistant via WebSocket"
version: "1.0.1"
slug: "homedoudou"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
options:
  websocket_port: 8080
schema:
  websocket_port: port